# Generated by Django 5.2.17 on 2026-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="hero_features/"
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hero Feature Pill",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NavLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                (
                    "url",
                    models.CharField(
                        default="#",
                        help_text='e.g. "#services" or "/services/".',
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Navigation Link",
                "ordering": ["order"],
            },
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="cta_label",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="cta_url",
        ),
        migrations.RemoveField(
            model_name="herosection",
            name="subheading",
        ),
        migrations.AddField(
            model_name="herosection",
            name="eyebrow_text",
            field=models.CharField(
                blank=True,
                help_text='Small label above the heading, e.g. "IT INFRASTRUCTURE SUPPORT".',
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="heading_highlight",
            field=models.CharField(
                blank=True,
                help_text='Second line shown in the accent color, e.g. "day and night."',
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="herosection",
            name="primary_cta_label",
            field=models.CharField(blank=True, default="Get a quote", max_length=50),
        ),
        migrations.AddField(
            model_name="herosection",
            name="primary_cta_url",
            field=models.CharField(blank=True, default="#contact", max_length=200),
        ),
        migrations.AddField(
            model_name="herosection",
            name="secondary_cta_label",
            field=models.CharField(blank=True, default="View services", max_length=50),
        ),
        migrations.AddField(
            model_name="herosection",
            name="secondary_cta_url",
            field=models.CharField(blank=True, default="#services", max_length=200),
        ),
        migrations.AddField(
            model_name="herosection",
            name="stat_caption",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="herosection",
            name="stat_value",
            field=models.CharField(
                blank=True,
                help_text='Small stat badge shown over the hero image, e.g. "99.97%".',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_cta_label",
            field=models.CharField(blank=True, default="Get a quote", max_length=50),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_cta_url",
            field=models.CharField(blank=True, default="#contact", max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_subtitle",
            field=models.CharField(
                blank=True,
                help_text='e.g. "IT · AUTOMATION · BPO", shown next to the logo in the header.',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="herosection",
            name="heading",
            field=models.CharField(
                help_text='Main heading text, e.g. "Keep your systems running".',
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="TrueTechs", max_length=100),
        ),
    ]
