# Generated by Django 5.2.17 on 2026-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_herofeature_navlink_remove_herosection_cta_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(
                        blank=True, help_text='e.g. "AI & AUTOMATION".', max_length=100
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text='e.g. "Put the repetitive work on autopilot."',
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="automation/"),
                ),
                (
                    "badge_label",
                    models.CharField(
                        blank=True,
                        default="Live automation running",
                        help_text="Small floating label shown over the image's top-left corner.",
                        max_length=100,
                    ),
                ),
                (
                    "badge_tags",
                    models.CharField(
                        blank=True,
                        help_text='Comma-separated short tags shown under the badge label, e.g. "AI, RPA, DOC, CRM".',
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Automation Section",
                "verbose_name_plural": "Automation Sections",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="icon_color",
            field=models.CharField(
                choices=[("blue", "Blue"), ("orange", "Orange")],
                default="blue",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="icon_key",
            field=models.CharField(
                choices=[
                    ("monitor", "Monitor"),
                    ("refresh", "Refresh / RPA"),
                    ("document", "Document"),
                    ("grid", "Dashboard / CRM"),
                ],
                default="monitor",
                help_text="Built-in icon shown in the colored square — no image upload needed.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Optional: upload a custom icon image to override the built-in one above.",
                null=True,
                upload_to="services/",
            ),
        ),
    ]
