# Generated by Django 5.2.17 on 2026-09-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_automationsection_service_icon_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CtaBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=150)),
                ("subheading", models.CharField(blank=True, max_length=200)),
                (
                    "button_label",
                    models.CharField(blank=True, default="Get started", max_length=50),
                ),
                (
                    "button_url",
                    models.CharField(blank=True, default="#contact", max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "CTA Banner",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="automationsection",
            name="badge2_subtitle",
            field=models.CharField(
                blank=True, default="Across 4 service lines", max_length=150
            ),
        ),
        migrations.AddField(
            model_name="automationsection",
            name="badge2_title",
            field=models.CharField(
                blank=True,
                default="Workflows automated",
                help_text="Second floating badge, shown over the image's bottom-right corner. Leave blank to hide it.",
                max_length=100,
            ),
        ),
    ]
