# Generated by Django 5.2.17 on 2026-09-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_ctabanner_automationsection_badge2_subtitle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BpoFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, help_text='e.g. "01".', max_length=10),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_key",
                    models.CharField(
                        choices=[
                            ("mic", "Microphone"),
                            ("briefcase", "Briefcase"),
                            ("document", "Document"),
                            ("user-plus", "User Plus"),
                        ],
                        default="mic",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Optional: upload a custom icon image to override the built-in one above.",
                        null=True,
                        upload_to="bpo_features/",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "BPO Feature Card",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BpoSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "BUSINESS PROCESS OUTSOURCING".',
                        max_length=100,
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text='First part of the heading, e.g. "Give your customers a".',
                        max_length=200,
                    ),
                ),
                (
                    "heading_highlight",
                    models.CharField(
                        blank=True,
                        help_text='Second part, e.g. "team that answers." (shown in the ink color, bold).',
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="bpo/")),
                (
                    "stat_value",
                    models.CharField(
                        blank=True,
                        default="24/7",
                        help_text="Top-left floating stat badge.",
                        max_length=20,
                    ),
                ),
                (
                    "stat_caption",
                    models.CharField(
                        blank=True, default="Support coverage", max_length=100
                    ),
                ),
                (
                    "badge_label",
                    models.CharField(
                        blank=True,
                        default="ACTIVE CHANNELS",
                        help_text="Small uppercase label in the bottom-right solid badge.",
                        max_length=100,
                    ),
                ),
                (
                    "badge_value",
                    models.CharField(
                        blank=True, default="Voice · Chat · Email", max_length=150
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text='Comma-separated pill row below the cards, e.g. "Voice, Email, Chat, WhatsApp, 24/7".',
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "BPO Section",
                "verbose_name_plural": "BPO Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CommitmentsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(blank=True, default="HOW WE WORK", max_length=100),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text='e.g. "Three commitments we hold to on every engagement."',
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Commitments Section",
                "verbose_name_plural": "Commitments Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CommitmentStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, help_text='e.g. "01".', max_length=10),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="commitments/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Commitment Step",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContactSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(
                        blank=True, default="GET IN TOUCH", max_length=100
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text='e.g. "Tell us what your operation needs."',
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "background_image",
                    models.ImageField(blank=True, null=True, upload_to="contact/"),
                ),
                (
                    "bullets",
                    models.TextField(
                        blank=True, help_text="One checklist bullet per line."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Contact Section",
                "verbose_name_plural": "Contact Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("service", models.CharField(blank=True, max_length=150)),
                ("requirement", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="FaqItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ Item",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FaqSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(blank=True, default="QUESTIONS", max_length=100),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text='e.g. "What clients ask before they start."',
                        max_length=200,
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="faq/")),
                ("quote_text", models.CharField(blank=True, max_length=300)),
                (
                    "quote_author",
                    models.CharField(blank=True, default="TrueTechs", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ Section",
                "verbose_name_plural": "FAQ Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "column",
                    models.CharField(
                        choices=[
                            ("quick_links", "Quick Links"),
                            ("services", "Services"),
                        ],
                        default="quick_links",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("url", models.CharField(default="#", max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Footer Link",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="InfoStripItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        choices=[
                            ("map-pin", "Map Pin"),
                            ("mail", "Mail"),
                            ("clock", "Clock"),
                            ("bolt", "Bolt"),
                        ],
                        default="map-pin",
                        max_length=20,
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        choices=[("orange", "Orange"), ("blue", "Blue")],
                        default="orange",
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='e.g. "Dubai — Head Office".', max_length=100
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Info Strip Item",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text='Small pin label, e.g. "HEAD OFFICE".', max_length=50
                    ),
                ),
                (
                    "label_color",
                    models.CharField(
                        choices=[("orange", "Orange"), ("blue", "Blue")],
                        default="orange",
                        max_length=10,
                    ),
                ),
                (
                    "city",
                    models.CharField(help_text='e.g. "Dubai, UAE".', max_length=100),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Commercial relationship".',
                        max_length=150,
                    ),
                ),
                (
                    "timezone_label",
                    models.CharField(
                        blank=True, help_text='e.g. "GST · UTC+4".', max_length=50
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "toggle_label",
                    models.CharField(
                        blank=True,
                        help_text='Short label for the toggle pill, e.g. "DUBAI".',
                        max_length=30,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="offices/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="OfficesSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(
                        blank=True, default="WHERE WE WORK FROM", max_length=100
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text='e.g. "Dubai for the relationship, Chennai for the engineering."',
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "highlight_title",
                    models.CharField(
                        blank=True, default="Around the clock", max_length=100
                    ),
                ),
                ("highlight_description", models.CharField(blank=True, max_length=250)),
                (
                    "highlight_channels",
                    models.CharField(
                        blank=True,
                        help_text='Comma-separated pill list, e.g. "Voice, Chat, Email". Leave blank to hide.',
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Offices Section",
                "verbose_name_plural": "Offices Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProcessSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(blank=True, default="OUR PROCESS", max_length=100),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text='e.g. "From first assessment to steady state."',
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Process Section",
                "verbose_name_plural": "Process Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, help_text='e.g. "01".', max_length=10),
                ),
                (
                    "icon_key",
                    models.CharField(
                        choices=[
                            ("target", "Target"),
                            ("nodes", "Nodes / Plan"),
                            ("link", "Link / Implement"),
                            ("grid", "Dashboard / Monitor"),
                            ("headset", "Headset / Support"),
                            ("sparkles", "Sparkles / Optimise"),
                        ],
                        default="target",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Process Step",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, help_text='e.g. "01".', max_length=10),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='e.g. "24/7 IT Infrastructure Support".',
                        max_length=100,
                    ),
                ),
                (
                    "icon_key",
                    models.CharField(
                        choices=[
                            ("monitor", "Monitor"),
                            ("refresh", "Refresh"),
                            ("document", "Document"),
                            ("grid", "Grid"),
                            ("shield", "Shield"),
                            ("dollar", "Dollar"),
                            ("clock", "Clock"),
                            ("trending-up", "Trending Up"),
                            ("users", "Users"),
                            ("bolt", "Bolt"),
                            ("mic", "Mic"),
                            ("briefcase", "Briefcase"),
                        ],
                        default="grid",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_lines/"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Short summary shown under the title in the detail panel.",
                        max_length=200,
                    ),
                ),
                (
                    "bullets",
                    models.TextField(
                        blank=True, help_text="One checklist bullet per line."
                    ),
                ),
                (
                    "button_label",
                    models.CharField(
                        blank=True, default="Enquire About This Service", max_length=50
                    ),
                ),
                (
                    "button_url",
                    models.CharField(blank=True, default="#contact", max_length=200),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service Line",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceLinesSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(blank=True, default="WHAT WE DO", max_length=100),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text='e.g. "Eight service lines, one point of contact."',
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Service Lines Section",
                "verbose_name_plural": "Service Lines Sections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhyUsFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon_key",
                    models.CharField(
                        choices=[
                            ("shield", "Shield"),
                            ("dollar", "Dollar"),
                            ("bolt", "Bolt"),
                            ("clock", "Clock"),
                            ("trending-up", "Trending Up"),
                            ("users", "Users"),
                        ],
                        default="shield",
                        max_length=20,
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        choices=[("blue", "Blue"), ("orange", "Orange")],
                        default="blue",
                        max_length=10,
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Optional: upload a custom icon image to override the built-in one above.",
                        null=True,
                        upload_to="whyus_features/",
                    ),
                ),
                (
                    "column",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")],
                        default="left",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Why Us Feature Card",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhyUsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "eyebrow_text",
                    models.CharField(
                        blank=True, default="WHY WORK WITH US", max_length=100
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text='e.g. "Support measured by what it changes in your operation."',
                        max_length=200,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="whyus/")),
                (
                    "badge_label",
                    models.CharField(blank=True, default="One partner", max_length=100),
                ),
                (
                    "badge_value",
                    models.CharField(
                        blank=True, default="8 service lines", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Why Us Section",
                "verbose_name_plural": "Why Us Sections",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_description",
            field=models.TextField(
                blank=True,
                help_text='e.g. "IT infrastructure, automation and business process operations — delivered from Dubai and Chennai."',
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_tagline",
            field=models.CharField(
                blank=True, default="24/7 monitoring and service desk", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="youtube_url",
            field=models.URLField(blank=True),
        ),
    ]
